/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrainRouteImport } from './routes/brain'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as CollaborationRouteImport } from './routes/collaboration'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as HelpRouteImport } from './routes/help'
import { Route as IjpRouteImport } from './routes/ijp'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as MastersRouteImport } from './routes/masters'
import { Route as MatchingRouteImport } from './routes/matching'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as OrganisationRouteImport } from './routes/organisation'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PlatformAgentsRouteImport } from './routes/platform-agents'
import { Route as PlatformAiUsageRouteImport } from './routes/platform-ai-usage'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RoiRouteImport } from './routes/roi'
import { Route as ScreeningRouteImport } from './routes/screening'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as AgentsObservabilityRouteImport } from './routes/agents.observability'
import { Route as AgentsRegisterRouteImport } from './routes/agents.register'
import { Route as AgentsSettingsRouteImport } from './routes/agents.settings'
import { Route as ApplyIdRouteImport } from './routes/apply.$id'
import { Route as AssessTokenRouteImport } from './routes/assess.$token'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as CandidatesIndexRouteImport } from './routes/candidates.index'
import { Route as CandidatesIdRouteImport } from './routes/candidates.$id'
import { Route as InterviewsIndexRouteImport } from './routes/interviews.index'
import { Route as InterviewsMineRouteImport } from './routes/interviews.mine'
import { Route as RequisitionsIndexRouteImport } from './routes/requisitions.index'
import { Route as RequisitionsIdRouteImport } from './routes/requisitions.$id'
import { Route as ScheduleTokenRouteImport } from './routes/schedule.$token'
import { Route as ApiAuthChangePasswordRouteImport } from './routes/api/auth/change-password'
import { Route as ApiAuthConfirmRouteImport } from './routes/api/auth/confirm'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthRequestResetRouteImport } from './routes/api/auth/request-reset'
import { Route as ApiAuthResetRouteImport } from './routes/api/auth/reset'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiPublicAgentTickRouteImport } from './routes/api/public/agent-tick'
import { Route as ApiPublicBoardSyncRouteImport } from './routes/api/public/board-sync'
import { Route as ApiPublicCaptureRouteImport } from './routes/api/public/capture'
import { Route as ApiPublicInboundEmailRouteImport } from './routes/api/public/inbound-email'
import { Route as ApiPublicInboxSyncRouteImport } from './routes/api/public/inbox-sync'
import { Route as ApiPublicProcessEmailOutboxRouteImport } from './routes/api/public/process-email-outbox'
import { Route as ApiPublicScreeningPrepRouteImport } from './routes/api/public/screening-prep'
import { Route as ApiPublicSyncCandidatesRouteImport } from './routes/api/public/sync-candidates'
import { Route as ApiPublicSyncHrmsRouteImport } from './routes/api/public/sync-hrms'
import { Route as ApiPublicLinkedinCallbackRouteImport } from './routes/api/public/linkedin/callback'
import { Route as ApiPublicBoardsProviderTokenRouteImport } from './routes/api/public/boards/$provider.$token'
import { Route as ApiPublicIntegrationsGoogleCallbackRouteImport } from './routes/api/public/integrations/google/callback'
import { Route as ApiPublicIntegrationsMicrosoftCallbackRouteImport } from './routes/api/public/integrations/microsoft/callback'
import { Route as ApiPublicIntegrationsZoomCallbackRouteImport } from './routes/api/public/integrations/zoom/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainRoute = BrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborationRoute = CollaborationRouteImport.update({
  id: '/collaboration',
  path: '/collaboration',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const IjpRoute = IjpRouteImport.update({
  id: '/ijp',
  path: '/ijp',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersRoute = MastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchingRoute = MatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationRoute = OrganisationRouteImport.update({
  id: '/organisation',
  path: '/organisation',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAgentsRoute = PlatformAgentsRouteImport.update({
  id: '/platform-agents',
  path: '/platform-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAiUsageRoute = PlatformAiUsageRouteImport.update({
  id: '/platform-ai-usage',
  path: '/platform-ai-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RoiRoute = RoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningRoute = ScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsObservabilityRoute = AgentsObservabilityRouteImport.update({
  id: '/agents/observability',
  path: '/agents/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRegisterRoute = AgentsRegisterRouteImport.update({
  id: '/agents/register',
  path: '/agents/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsSettingsRoute = AgentsSettingsRouteImport.update({
  id: '/agents/settings',
  path: '/agents/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyIdRoute = ApplyIdRouteImport.update({
  id: '/apply/$id',
  path: '/apply/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessTokenRoute = AssessTokenRouteImport.update({
  id: '/assess/$token',
  path: '/assess/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesIndexRoute = CandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesIdRoute = CandidatesIdRouteImport.update({
  id: '/candidates/$id',
  path: '/candidates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsIndexRoute = InterviewsIndexRouteImport.update({
  id: '/interviews/',
  path: '/interviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsMineRoute = InterviewsMineRouteImport.update({
  id: '/interviews/mine',
  path: '/interviews/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const RequisitionsIndexRoute = RequisitionsIndexRouteImport.update({
  id: '/requisitions/',
  path: '/requisitions/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequisitionsIdRoute = RequisitionsIdRouteImport.update({
  id: '/requisitions/$id',
  path: '/requisitions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleTokenRoute = ScheduleTokenRouteImport.update({
  id: '/schedule/$token',
  path: '/schedule/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthChangePasswordRoute = ApiAuthChangePasswordRouteImport.update({
  id: '/api/auth/change-password',
  path: '/api/auth/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthConfirmRoute = ApiAuthConfirmRouteImport.update({
  id: '/api/auth/confirm',
  path: '/api/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRequestResetRoute = ApiAuthRequestResetRouteImport.update({
  id: '/api/auth/request-reset',
  path: '/api/auth/request-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthResetRoute = ApiAuthResetRouteImport.update({
  id: '/api/auth/reset',
  path: '/api/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentTickRoute = ApiPublicAgentTickRouteImport.update({
  id: '/api/public/agent-tick',
  path: '/api/public/agent-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBoardSyncRoute = ApiPublicBoardSyncRouteImport.update({
  id: '/api/public/board-sync',
  path: '/api/public/board-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCaptureRoute = ApiPublicCaptureRouteImport.update({
  id: '/api/public/capture',
  path: '/api/public/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInboundEmailRoute = ApiPublicInboundEmailRouteImport.update({
  id: '/api/public/inbound-email',
  path: '/api/public/inbound-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInboxSyncRoute = ApiPublicInboxSyncRouteImport.update({
  id: '/api/public/inbox-sync',
  path: '/api/public/inbox-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProcessEmailOutboxRoute =
  ApiPublicProcessEmailOutboxRouteImport.update({
    id: '/api/public/process-email-outbox',
    path: '/api/public/process-email-outbox',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicScreeningPrepRoute = ApiPublicScreeningPrepRouteImport.update({
  id: '/api/public/screening-prep',
  path: '/api/public/screening-prep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncCandidatesRoute = ApiPublicSyncCandidatesRouteImport.update({
  id: '/api/public/sync-candidates',
  path: '/api/public/sync-candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncHrmsRoute = ApiPublicSyncHrmsRouteImport.update({
  id: '/api/public/sync-hrms',
  path: '/api/public/sync-hrms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLinkedinCallbackRoute =
  ApiPublicLinkedinCallbackRouteImport.update({
    id: '/api/public/linkedin/callback',
    path: '/api/public/linkedin/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBoardsProviderTokenRoute =
  ApiPublicBoardsProviderTokenRouteImport.update({
    id: '/api/public/boards/$provider/$token',
    path: '/api/public/boards/$provider/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntegrationsGoogleCallbackRoute =
  ApiPublicIntegrationsGoogleCallbackRouteImport.update({
    id: '/api/public/integrations/google/callback',
    path: '/api/public/integrations/google/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntegrationsMicrosoftCallbackRoute =
  ApiPublicIntegrationsMicrosoftCallbackRouteImport.update({
    id: '/api/public/integrations/microsoft/callback',
    path: '/api/public/integrations/microsoft/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntegrationsZoomCallbackRoute =
  ApiPublicIntegrationsZoomCallbackRouteImport.update({
    id: '/api/public/integrations/zoom/callback',
    path: '/api/public/integrations/zoom/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brain': typeof BrainRoute
  '/catalogue': typeof CatalogueRoute
  '/collaboration': typeof CollaborationRoute
  '/cookies': typeof CookiesRoute
  '/desk': typeof DeskRoute
  '/help': typeof HelpRoute
  '/ijp': typeof IjpRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/masters': typeof MastersRoute
  '/matching': typeof MatchingRoute
  '/offers': typeof OffersRoute
  '/organisation': typeof OrganisationRoute
  '/platform': typeof PlatformRoute
  '/platform-agents': typeof PlatformAgentsRoute
  '/platform-ai-usage': typeof PlatformAiUsageRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/roi': typeof RoiRoute
  '/screening': typeof ScreeningRoute
  '/team': typeof TeamRoute
  '/templates': typeof TemplatesRoute
  '/agents/observability': typeof AgentsObservabilityRoute
  '/agents/register': typeof AgentsRegisterRoute
  '/agents/settings': typeof AgentsSettingsRoute
  '/apply/$id': typeof ApplyIdRoute
  '/assess/$token': typeof AssessTokenRoute
  '/auth/reset': typeof AuthResetRoute
  '/candidates/$id': typeof CandidatesIdRoute
  '/interviews/mine': typeof InterviewsMineRoute
  '/requisitions/$id': typeof RequisitionsIdRoute
  '/schedule/$token': typeof ScheduleTokenRoute
  '/agents/': typeof AgentsIndexRoute
  '/candidates/': typeof CandidatesIndexRoute
  '/interviews/': typeof InterviewsIndexRoute
  '/requisitions/': typeof RequisitionsIndexRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/confirm': typeof ApiAuthConfirmRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/request-reset': typeof ApiAuthRequestResetRoute
  '/api/auth/reset': typeof ApiAuthResetRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/public/agent-tick': typeof ApiPublicAgentTickRoute
  '/api/public/board-sync': typeof ApiPublicBoardSyncRoute
  '/api/public/capture': typeof ApiPublicCaptureRoute
  '/api/public/inbound-email': typeof ApiPublicInboundEmailRoute
  '/api/public/inbox-sync': typeof ApiPublicInboxSyncRoute
  '/api/public/process-email-outbox': typeof ApiPublicProcessEmailOutboxRoute
  '/api/public/screening-prep': typeof ApiPublicScreeningPrepRoute
  '/api/public/sync-candidates': typeof ApiPublicSyncCandidatesRoute
  '/api/public/sync-hrms': typeof ApiPublicSyncHrmsRoute
  '/api/public/linkedin/callback': typeof ApiPublicLinkedinCallbackRoute
  '/api/public/boards/$provider/$token': typeof ApiPublicBoardsProviderTokenRoute
  '/api/public/integrations/google/callback': typeof ApiPublicIntegrationsGoogleCallbackRoute
  '/api/public/integrations/microsoft/callback': typeof ApiPublicIntegrationsMicrosoftCallbackRoute
  '/api/public/integrations/zoom/callback': typeof ApiPublicIntegrationsZoomCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brain': typeof BrainRoute
  '/catalogue': typeof CatalogueRoute
  '/collaboration': typeof CollaborationRoute
  '/cookies': typeof CookiesRoute
  '/desk': typeof DeskRoute
  '/help': typeof HelpRoute
  '/ijp': typeof IjpRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/masters': typeof MastersRoute
  '/matching': typeof MatchingRoute
  '/offers': typeof OffersRoute
  '/organisation': typeof OrganisationRoute
  '/platform': typeof PlatformRoute
  '/platform-agents': typeof PlatformAgentsRoute
  '/platform-ai-usage': typeof PlatformAiUsageRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/roi': typeof RoiRoute
  '/screening': typeof ScreeningRoute
  '/team': typeof TeamRoute
  '/templates': typeof TemplatesRoute
  '/agents/observability': typeof AgentsObservabilityRoute
  '/agents/register': typeof AgentsRegisterRoute
  '/agents/settings': typeof AgentsSettingsRoute
  '/apply/$id': typeof ApplyIdRoute
  '/assess/$token': typeof AssessTokenRoute
  '/auth/reset': typeof AuthResetRoute
  '/candidates/$id': typeof CandidatesIdRoute
  '/interviews/mine': typeof InterviewsMineRoute
  '/requisitions/$id': typeof RequisitionsIdRoute
  '/schedule/$token': typeof ScheduleTokenRoute
  '/agents': typeof AgentsIndexRoute
  '/candidates': typeof CandidatesIndexRoute
  '/interviews': typeof InterviewsIndexRoute
  '/requisitions': typeof RequisitionsIndexRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/confirm': typeof ApiAuthConfirmRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/request-reset': typeof ApiAuthRequestResetRoute
  '/api/auth/reset': typeof ApiAuthResetRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/public/agent-tick': typeof ApiPublicAgentTickRoute
  '/api/public/board-sync': typeof ApiPublicBoardSyncRoute
  '/api/public/capture': typeof ApiPublicCaptureRoute
  '/api/public/inbound-email': typeof ApiPublicInboundEmailRoute
  '/api/public/inbox-sync': typeof ApiPublicInboxSyncRoute
  '/api/public/process-email-outbox': typeof ApiPublicProcessEmailOutboxRoute
  '/api/public/screening-prep': typeof ApiPublicScreeningPrepRoute
  '/api/public/sync-candidates': typeof ApiPublicSyncCandidatesRoute
  '/api/public/sync-hrms': typeof ApiPublicSyncHrmsRoute
  '/api/public/linkedin/callback': typeof ApiPublicLinkedinCallbackRoute
  '/api/public/boards/$provider/$token': typeof ApiPublicBoardsProviderTokenRoute
  '/api/public/integrations/google/callback': typeof ApiPublicIntegrationsGoogleCallbackRoute
  '/api/public/integrations/microsoft/callback': typeof ApiPublicIntegrationsMicrosoftCallbackRoute
  '/api/public/integrations/zoom/callback': typeof ApiPublicIntegrationsZoomCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brain': typeof BrainRoute
  '/catalogue': typeof CatalogueRoute
  '/collaboration': typeof CollaborationRoute
  '/cookies': typeof CookiesRoute
  '/desk': typeof DeskRoute
  '/help': typeof HelpRoute
  '/ijp': typeof IjpRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/masters': typeof MastersRoute
  '/matching': typeof MatchingRoute
  '/offers': typeof OffersRoute
  '/organisation': typeof OrganisationRoute
  '/platform': typeof PlatformRoute
  '/platform-agents': typeof PlatformAgentsRoute
  '/platform-ai-usage': typeof PlatformAiUsageRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/roi': typeof RoiRoute
  '/screening': typeof ScreeningRoute
  '/team': typeof TeamRoute
  '/templates': typeof TemplatesRoute
  '/agents/observability': typeof AgentsObservabilityRoute
  '/agents/register': typeof AgentsRegisterRoute
  '/agents/settings': typeof AgentsSettingsRoute
  '/apply/$id': typeof ApplyIdRoute
  '/assess/$token': typeof AssessTokenRoute
  '/auth/reset': typeof AuthResetRoute
  '/candidates/$id': typeof CandidatesIdRoute
  '/interviews/mine': typeof InterviewsMineRoute
  '/requisitions/$id': typeof RequisitionsIdRoute
  '/schedule/$token': typeof ScheduleTokenRoute
  '/agents/': typeof AgentsIndexRoute
  '/candidates/': typeof CandidatesIndexRoute
  '/interviews/': typeof InterviewsIndexRoute
  '/requisitions/': typeof RequisitionsIndexRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/confirm': typeof ApiAuthConfirmRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/request-reset': typeof ApiAuthRequestResetRoute
  '/api/auth/reset': typeof ApiAuthResetRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/public/agent-tick': typeof ApiPublicAgentTickRoute
  '/api/public/board-sync': typeof ApiPublicBoardSyncRoute
  '/api/public/capture': typeof ApiPublicCaptureRoute
  '/api/public/inbound-email': typeof ApiPublicInboundEmailRoute
  '/api/public/inbox-sync': typeof ApiPublicInboxSyncRoute
  '/api/public/process-email-outbox': typeof ApiPublicProcessEmailOutboxRoute
  '/api/public/screening-prep': typeof ApiPublicScreeningPrepRoute
  '/api/public/sync-candidates': typeof ApiPublicSyncCandidatesRoute
  '/api/public/sync-hrms': typeof ApiPublicSyncHrmsRoute
  '/api/public/linkedin/callback': typeof ApiPublicLinkedinCallbackRoute
  '/api/public/boards/$provider/$token': typeof ApiPublicBoardsProviderTokenRoute
  '/api/public/integrations/google/callback': typeof ApiPublicIntegrationsGoogleCallbackRoute
  '/api/public/integrations/microsoft/callback': typeof ApiPublicIntegrationsMicrosoftCallbackRoute
  '/api/public/integrations/zoom/callback': typeof ApiPublicIntegrationsZoomCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brain'
    | '/catalogue'
    | '/collaboration'
    | '/cookies'
    | '/desk'
    | '/help'
    | '/ijp'
    | '/inbox'
    | '/integrations'
    | '/masters'
    | '/matching'
    | '/offers'
    | '/organisation'
    | '/platform'
    | '/platform-agents'
    | '/platform-ai-usage'
    | '/privacy'
    | '/reports'
    | '/roi'
    | '/screening'
    | '/team'
    | '/templates'
    | '/agents/observability'
    | '/agents/register'
    | '/agents/settings'
    | '/apply/$id'
    | '/assess/$token'
    | '/auth/reset'
    | '/candidates/$id'
    | '/interviews/mine'
    | '/requisitions/$id'
    | '/schedule/$token'
    | '/agents/'
    | '/candidates/'
    | '/interviews/'
    | '/requisitions/'
    | '/api/auth/change-password'
    | '/api/auth/confirm'
    | '/api/auth/login'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/request-reset'
    | '/api/auth/reset'
    | '/api/auth/session'
    | '/api/public/agent-tick'
    | '/api/public/board-sync'
    | '/api/public/capture'
    | '/api/public/inbound-email'
    | '/api/public/inbox-sync'
    | '/api/public/process-email-outbox'
    | '/api/public/screening-prep'
    | '/api/public/sync-candidates'
    | '/api/public/sync-hrms'
    | '/api/public/linkedin/callback'
    | '/api/public/boards/$provider/$token'
    | '/api/public/integrations/google/callback'
    | '/api/public/integrations/microsoft/callback'
    | '/api/public/integrations/zoom/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brain'
    | '/catalogue'
    | '/collaboration'
    | '/cookies'
    | '/desk'
    | '/help'
    | '/ijp'
    | '/inbox'
    | '/integrations'
    | '/masters'
    | '/matching'
    | '/offers'
    | '/organisation'
    | '/platform'
    | '/platform-agents'
    | '/platform-ai-usage'
    | '/privacy'
    | '/reports'
    | '/roi'
    | '/screening'
    | '/team'
    | '/templates'
    | '/agents/observability'
    | '/agents/register'
    | '/agents/settings'
    | '/apply/$id'
    | '/assess/$token'
    | '/auth/reset'
    | '/candidates/$id'
    | '/interviews/mine'
    | '/requisitions/$id'
    | '/schedule/$token'
    | '/agents'
    | '/candidates'
    | '/interviews'
    | '/requisitions'
    | '/api/auth/change-password'
    | '/api/auth/confirm'
    | '/api/auth/login'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/request-reset'
    | '/api/auth/reset'
    | '/api/auth/session'
    | '/api/public/agent-tick'
    | '/api/public/board-sync'
    | '/api/public/capture'
    | '/api/public/inbound-email'
    | '/api/public/inbox-sync'
    | '/api/public/process-email-outbox'
    | '/api/public/screening-prep'
    | '/api/public/sync-candidates'
    | '/api/public/sync-hrms'
    | '/api/public/linkedin/callback'
    | '/api/public/boards/$provider/$token'
    | '/api/public/integrations/google/callback'
    | '/api/public/integrations/microsoft/callback'
    | '/api/public/integrations/zoom/callback'
  id:
    | '__root__'
    | '/'
    | '/brain'
    | '/catalogue'
    | '/collaboration'
    | '/cookies'
    | '/desk'
    | '/help'
    | '/ijp'
    | '/inbox'
    | '/integrations'
    | '/masters'
    | '/matching'
    | '/offers'
    | '/organisation'
    | '/platform'
    | '/platform-agents'
    | '/platform-ai-usage'
    | '/privacy'
    | '/reports'
    | '/roi'
    | '/screening'
    | '/team'
    | '/templates'
    | '/agents/observability'
    | '/agents/register'
    | '/agents/settings'
    | '/apply/$id'
    | '/assess/$token'
    | '/auth/reset'
    | '/candidates/$id'
    | '/interviews/mine'
    | '/requisitions/$id'
    | '/schedule/$token'
    | '/agents/'
    | '/candidates/'
    | '/interviews/'
    | '/requisitions/'
    | '/api/auth/change-password'
    | '/api/auth/confirm'
    | '/api/auth/login'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/request-reset'
    | '/api/auth/reset'
    | '/api/auth/session'
    | '/api/public/agent-tick'
    | '/api/public/board-sync'
    | '/api/public/capture'
    | '/api/public/inbound-email'
    | '/api/public/inbox-sync'
    | '/api/public/process-email-outbox'
    | '/api/public/screening-prep'
    | '/api/public/sync-candidates'
    | '/api/public/sync-hrms'
    | '/api/public/linkedin/callback'
    | '/api/public/boards/$provider/$token'
    | '/api/public/integrations/google/callback'
    | '/api/public/integrations/microsoft/callback'
    | '/api/public/integrations/zoom/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrainRoute: typeof BrainRoute
  CatalogueRoute: typeof CatalogueRoute
  CollaborationRoute: typeof CollaborationRoute
  CookiesRoute: typeof CookiesRoute
  DeskRoute: typeof DeskRoute
  HelpRoute: typeof HelpRoute
  IjpRoute: typeof IjpRoute
  InboxRoute: typeof InboxRoute
  IntegrationsRoute: typeof IntegrationsRoute
  MastersRoute: typeof MastersRoute
  MatchingRoute: typeof MatchingRoute
  OffersRoute: typeof OffersRoute
  OrganisationRoute: typeof OrganisationRoute
  PlatformRoute: typeof PlatformRoute
  PlatformAgentsRoute: typeof PlatformAgentsRoute
  PlatformAiUsageRoute: typeof PlatformAiUsageRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportsRoute: typeof ReportsRoute
  RoiRoute: typeof RoiRoute
  ScreeningRoute: typeof ScreeningRoute
  TeamRoute: typeof TeamRoute
  TemplatesRoute: typeof TemplatesRoute
  AgentsObservabilityRoute: typeof AgentsObservabilityRoute
  AgentsRegisterRoute: typeof AgentsRegisterRoute
  AgentsSettingsRoute: typeof AgentsSettingsRoute
  ApplyIdRoute: typeof ApplyIdRoute
  AssessTokenRoute: typeof AssessTokenRoute
  AuthResetRoute: typeof AuthResetRoute
  CandidatesIdRoute: typeof CandidatesIdRoute
  InterviewsMineRoute: typeof InterviewsMineRoute
  RequisitionsIdRoute: typeof RequisitionsIdRoute
  ScheduleTokenRoute: typeof ScheduleTokenRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  CandidatesIndexRoute: typeof CandidatesIndexRoute
  InterviewsIndexRoute: typeof InterviewsIndexRoute
  RequisitionsIndexRoute: typeof RequisitionsIndexRoute
  ApiAuthChangePasswordRoute: typeof ApiAuthChangePasswordRoute
  ApiAuthConfirmRoute: typeof ApiAuthConfirmRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiAuthRequestResetRoute: typeof ApiAuthRequestResetRoute
  ApiAuthResetRoute: typeof ApiAuthResetRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiPublicAgentTickRoute: typeof ApiPublicAgentTickRoute
  ApiPublicBoardSyncRoute: typeof ApiPublicBoardSyncRoute
  ApiPublicCaptureRoute: typeof ApiPublicCaptureRoute
  ApiPublicInboundEmailRoute: typeof ApiPublicInboundEmailRoute
  ApiPublicInboxSyncRoute: typeof ApiPublicInboxSyncRoute
  ApiPublicProcessEmailOutboxRoute: typeof ApiPublicProcessEmailOutboxRoute
  ApiPublicScreeningPrepRoute: typeof ApiPublicScreeningPrepRoute
  ApiPublicSyncCandidatesRoute: typeof ApiPublicSyncCandidatesRoute
  ApiPublicSyncHrmsRoute: typeof ApiPublicSyncHrmsRoute
  ApiPublicLinkedinCallbackRoute: typeof ApiPublicLinkedinCallbackRoute
  ApiPublicBoardsProviderTokenRoute: typeof ApiPublicBoardsProviderTokenRoute
  ApiPublicIntegrationsGoogleCallbackRoute: typeof ApiPublicIntegrationsGoogleCallbackRoute
  ApiPublicIntegrationsMicrosoftCallbackRoute: typeof ApiPublicIntegrationsMicrosoftCallbackRoute
  ApiPublicIntegrationsZoomCallbackRoute: typeof ApiPublicIntegrationsZoomCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain': {
      id: '/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof BrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaboration': {
      id: '/collaboration'
      path: '/collaboration'
      fullPath: '/collaboration'
      preLoaderRoute: typeof CollaborationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ijp': {
      id: '/ijp'
      path: '/ijp'
      fullPath: '/ijp'
      preLoaderRoute: typeof IjpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters': {
      id: '/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof MastersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matching': {
      id: '/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof MatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisation': {
      id: '/organisation'
      path: '/organisation'
      fullPath: '/organisation'
      preLoaderRoute: typeof OrganisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-agents': {
      id: '/platform-agents'
      path: '/platform-agents'
      fullPath: '/platform-agents'
      preLoaderRoute: typeof PlatformAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-ai-usage': {
      id: '/platform-ai-usage'
      path: '/platform-ai-usage'
      fullPath: '/platform-ai-usage'
      preLoaderRoute: typeof PlatformAiUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roi': {
      id: '/roi'
      path: '/roi'
      fullPath: '/roi'
      preLoaderRoute: typeof RoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening': {
      id: '/screening'
      path: '/screening'
      fullPath: '/screening'
      preLoaderRoute: typeof ScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/observability': {
      id: '/agents/observability'
      path: '/agents/observability'
      fullPath: '/agents/observability'
      preLoaderRoute: typeof AgentsObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/register': {
      id: '/agents/register'
      path: '/agents/register'
      fullPath: '/agents/register'
      preLoaderRoute: typeof AgentsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/settings': {
      id: '/agents/settings'
      path: '/agents/settings'
      fullPath: '/agents/settings'
      preLoaderRoute: typeof AgentsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$id': {
      id: '/apply/$id'
      path: '/apply/$id'
      fullPath: '/apply/$id'
      preLoaderRoute: typeof ApplyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess/$token': {
      id: '/assess/$token'
      path: '/assess/$token'
      fullPath: '/assess/$token'
      preLoaderRoute: typeof AssessTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/': {
      id: '/candidates/'
      path: '/candidates'
      fullPath: '/candidates/'
      preLoaderRoute: typeof CandidatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/$id': {
      id: '/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof CandidatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews/': {
      id: '/interviews/'
      path: '/interviews'
      fullPath: '/interviews/'
      preLoaderRoute: typeof InterviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews/mine': {
      id: '/interviews/mine'
      path: '/interviews/mine'
      fullPath: '/interviews/mine'
      preLoaderRoute: typeof InterviewsMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requisitions/': {
      id: '/requisitions/'
      path: '/requisitions'
      fullPath: '/requisitions/'
      preLoaderRoute: typeof RequisitionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requisitions/$id': {
      id: '/requisitions/$id'
      path: '/requisitions/$id'
      fullPath: '/requisitions/$id'
      preLoaderRoute: typeof RequisitionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/$token': {
      id: '/schedule/$token'
      path: '/schedule/$token'
      fullPath: '/schedule/$token'
      preLoaderRoute: typeof ScheduleTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/change-password': {
      id: '/api/auth/change-password'
      path: '/api/auth/change-password'
      fullPath: '/api/auth/change-password'
      preLoaderRoute: typeof ApiAuthChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/confirm': {
      id: '/api/auth/confirm'
      path: '/api/auth/confirm'
      fullPath: '/api/auth/confirm'
      preLoaderRoute: typeof ApiAuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/request-reset': {
      id: '/api/auth/request-reset'
      path: '/api/auth/request-reset'
      fullPath: '/api/auth/request-reset'
      preLoaderRoute: typeof ApiAuthRequestResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/reset': {
      id: '/api/auth/reset'
      path: '/api/auth/reset'
      fullPath: '/api/auth/reset'
      preLoaderRoute: typeof ApiAuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-tick': {
      id: '/api/public/agent-tick'
      path: '/api/public/agent-tick'
      fullPath: '/api/public/agent-tick'
      preLoaderRoute: typeof ApiPublicAgentTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/board-sync': {
      id: '/api/public/board-sync'
      path: '/api/public/board-sync'
      fullPath: '/api/public/board-sync'
      preLoaderRoute: typeof ApiPublicBoardSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/capture': {
      id: '/api/public/capture'
      path: '/api/public/capture'
      fullPath: '/api/public/capture'
      preLoaderRoute: typeof ApiPublicCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inbound-email': {
      id: '/api/public/inbound-email'
      path: '/api/public/inbound-email'
      fullPath: '/api/public/inbound-email'
      preLoaderRoute: typeof ApiPublicInboundEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inbox-sync': {
      id: '/api/public/inbox-sync'
      path: '/api/public/inbox-sync'
      fullPath: '/api/public/inbox-sync'
      preLoaderRoute: typeof ApiPublicInboxSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/process-email-outbox': {
      id: '/api/public/process-email-outbox'
      path: '/api/public/process-email-outbox'
      fullPath: '/api/public/process-email-outbox'
      preLoaderRoute: typeof ApiPublicProcessEmailOutboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/screening-prep': {
      id: '/api/public/screening-prep'
      path: '/api/public/screening-prep'
      fullPath: '/api/public/screening-prep'
      preLoaderRoute: typeof ApiPublicScreeningPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-candidates': {
      id: '/api/public/sync-candidates'
      path: '/api/public/sync-candidates'
      fullPath: '/api/public/sync-candidates'
      preLoaderRoute: typeof ApiPublicSyncCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-hrms': {
      id: '/api/public/sync-hrms'
      path: '/api/public/sync-hrms'
      fullPath: '/api/public/sync-hrms'
      preLoaderRoute: typeof ApiPublicSyncHrmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/linkedin/callback': {
      id: '/api/public/linkedin/callback'
      path: '/api/public/linkedin/callback'
      fullPath: '/api/public/linkedin/callback'
      preLoaderRoute: typeof ApiPublicLinkedinCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/boards/$provider/$token': {
      id: '/api/public/boards/$provider/$token'
      path: '/api/public/boards/$provider/$token'
      fullPath: '/api/public/boards/$provider/$token'
      preLoaderRoute: typeof ApiPublicBoardsProviderTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/google/callback': {
      id: '/api/public/integrations/google/callback'
      path: '/api/public/integrations/google/callback'
      fullPath: '/api/public/integrations/google/callback'
      preLoaderRoute: typeof ApiPublicIntegrationsGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/microsoft/callback': {
      id: '/api/public/integrations/microsoft/callback'
      path: '/api/public/integrations/microsoft/callback'
      fullPath: '/api/public/integrations/microsoft/callback'
      preLoaderRoute: typeof ApiPublicIntegrationsMicrosoftCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/zoom/callback': {
      id: '/api/public/integrations/zoom/callback'
      path: '/api/public/integrations/zoom/callback'
      fullPath: '/api/public/integrations/zoom/callback'
      preLoaderRoute: typeof ApiPublicIntegrationsZoomCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrainRoute: BrainRoute,
  CatalogueRoute: CatalogueRoute,
  CollaborationRoute: CollaborationRoute,
  CookiesRoute: CookiesRoute,
  DeskRoute: DeskRoute,
  HelpRoute: HelpRoute,
  IjpRoute: IjpRoute,
  InboxRoute: InboxRoute,
  IntegrationsRoute: IntegrationsRoute,
  MastersRoute: MastersRoute,
  MatchingRoute: MatchingRoute,
  OffersRoute: OffersRoute,
  OrganisationRoute: OrganisationRoute,
  PlatformRoute: PlatformRoute,
  PlatformAgentsRoute: PlatformAgentsRoute,
  PlatformAiUsageRoute: PlatformAiUsageRoute,
  PrivacyRoute: PrivacyRoute,
  ReportsRoute: ReportsRoute,
  RoiRoute: RoiRoute,
  ScreeningRoute: ScreeningRoute,
  TeamRoute: TeamRoute,
  TemplatesRoute: TemplatesRoute,
  AgentsObservabilityRoute: AgentsObservabilityRoute,
  AgentsRegisterRoute: AgentsRegisterRoute,
  AgentsSettingsRoute: AgentsSettingsRoute,
  ApplyIdRoute: ApplyIdRoute,
  AssessTokenRoute: AssessTokenRoute,
  AuthResetRoute: AuthResetRoute,
  CandidatesIdRoute: CandidatesIdRoute,
  InterviewsMineRoute: InterviewsMineRoute,
  RequisitionsIdRoute: RequisitionsIdRoute,
  ScheduleTokenRoute: ScheduleTokenRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  CandidatesIndexRoute: CandidatesIndexRoute,
  InterviewsIndexRoute: InterviewsIndexRoute,
  RequisitionsIndexRoute: RequisitionsIndexRoute,
  ApiAuthChangePasswordRoute: ApiAuthChangePasswordRoute,
  ApiAuthConfirmRoute: ApiAuthConfirmRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiAuthRequestResetRoute: ApiAuthRequestResetRoute,
  ApiAuthResetRoute: ApiAuthResetRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiPublicAgentTickRoute: ApiPublicAgentTickRoute,
  ApiPublicBoardSyncRoute: ApiPublicBoardSyncRoute,
  ApiPublicCaptureRoute: ApiPublicCaptureRoute,
  ApiPublicInboundEmailRoute: ApiPublicInboundEmailRoute,
  ApiPublicInboxSyncRoute: ApiPublicInboxSyncRoute,
  ApiPublicProcessEmailOutboxRoute: ApiPublicProcessEmailOutboxRoute,
  ApiPublicScreeningPrepRoute: ApiPublicScreeningPrepRoute,
  ApiPublicSyncCandidatesRoute: ApiPublicSyncCandidatesRoute,
  ApiPublicSyncHrmsRoute: ApiPublicSyncHrmsRoute,
  ApiPublicLinkedinCallbackRoute: ApiPublicLinkedinCallbackRoute,
  ApiPublicBoardsProviderTokenRoute: ApiPublicBoardsProviderTokenRoute,
  ApiPublicIntegrationsGoogleCallbackRoute:
    ApiPublicIntegrationsGoogleCallbackRoute,
  ApiPublicIntegrationsMicrosoftCallbackRoute:
    ApiPublicIntegrationsMicrosoftCallbackRoute,
  ApiPublicIntegrationsZoomCallbackRoute:
    ApiPublicIntegrationsZoomCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
